version: '3.8'

services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./internal/infra/docker/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ash
      POSTGRES_PASSWORD: strong_password
      TZ: UTC
    restart: "unless-stopped"

volumes:
  data:
    driver: local

networks:
  default:
    driver: bridge
